!obj:pylearn2.train.Train {
    dataset: &train !pkl: '../datasets/height_dataset_train.pkl',

    model: !obj:pylearn2.models.mlp.MLP {
        layers : [
            !obj:pylearn2.models.mlp.Sigmoid {
                layer_name: 'h0',
                dim: 361,
                sparse_init: 15,
                # Rather than using weight decay, we constrain the norms of the weight vectors
                # max_col_norm: 2.
            },
            !obj:pylearn2.models.mlp.Softmax {
                layer_name: 'y',
                # init_bias_target_marginals: *train,
                # Initialize the weights to all 0s
                irange: .0,
                n_classes: 1
            }
        ],
        nvis: 361,
    },

    # We train using SGD and momentum
    algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
        learning_rate: .1,
        batch_size : 5,
        learning_rule: !obj:pylearn2.training_algorithms.learning_rule.Momentum {
            init_momentum: .5,
        },
        # We monitor how well we're doing during training on a validation set
        monitoring_dataset: {
            'train' : *train,
            'valid' : !pkl: '../datasets/height_dataset_valid.pkl'
        },
        # We stop when validation set classification error hasn't decreased for 10 epochs
        termination_criterion: !obj:pylearn2.termination_criteria.And {
            criteria: [
                !obj:pylearn2.termination_criteria.MonitorBased {
                    channel_name: "valid_y_misclass",
                    prop_decrease: 0.,
                    N: 10
                },
                !obj:pylearn2.termination_criteria.EpochCounter {
                    max_epochs: 5
                }
            ]
        }
    },
    # We save the model whenever we improve on the validation set classification error
#    extensions: [
#        !obj:pylearn2.train_extensions.best_params.MonitorBasedSaveBest {
#             channel_name: 'valid_y_misclass',
#             save_path: "${PYLEARN2_TRAIN_FILE_FULL_STEM}_best.pkl"
#        },
#    ],
    save_path: "mlp.pkl",
    save_freq: 1
}
